# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Coding Snippets'
tagline:          'Code snippets that come in useful'
description:      'Little pieces of code that I have made use of during the course of various projects. Author <a href="https://www.twitter.com/crshnburn">@crshnburn</a>'
url:              http://crshnburn.github.io
baseurl:          /

author:
  name:           'Andrew Smithson'
  url:            https://twitter.com/crshnburn

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/crshnburn/crshnburn.github.io
